### ISSUE TITLE
Performance comparison c2crs

### ISSUE THREAD

**Issue by icedpanda** [Zyh716/WSDM2022-C2CRS#2]
Hi, thanks for sharing the source code.

Just wondering do you include all movie items as context items or just positive movie items? (e.g. liked movie)

From the code, it seems all items are treated as context items. However, paper-like `KECRS` use only positive items. Have you experimented using `C2CRS` with only positive items?

Thanks in advance

**Comment by Zyh716** [comment]
Hi, we include all movie items as context items in C2CRS. And We haven't experimented with using C2CRS with only positive items.

**Comment by icedpanda** [comment]
@Zyh716 thanks for the clarification
